### ISSUE TITLE
Category?

### ISSUE THREAD

**Issue by amandabee** [amandabee/Sewing-Emoji#1]
http://unicode.org/emoji/charts/emoji-ordering.html

Possible locations include:

> Activities > Sewing (after game, or between event and award)

> Objects > other object (least desireable)

> Objects > Sewing (between office and lock?)

Is there a better umbrella term that "sewing"? "fiber arts" seems fussy. "textiles"?

**Comment by amberleyromo** [comment]
I would suggest "crafting"? It's a wider umbrella, which I would think is a good thing. "Sewing" is extremely specific and narrow.
